// Installing the MCP Bridge device into a Studio One profile.
import { cpSync, mkdirSync, writeFileSync, rmSync, existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mailboxDir } from '../paths.js';

export const deviceSource = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'device', 'StudioOneMCP');
export const deviceTarget = (profile) => join(profile, 'User Devices', 'studio-one-mcp');

// Studio One's own files store file URLs unencoded ("file:///…/Studio One/…").
export function fileUrl(path) {
  const p = path.replace(/\\/g, '/');
  return 'file://' + (p.startsWith('/') ? '' : '/') + p;
}

export function installDevice({ profile, allowEval = false, mailbox = mailboxDir }) {
  const target = deviceTarget(profile);
  mkdirSync(target, { recursive: true });
  cpSync(deviceSource, target, { recursive: true });
  mkdirSync(mailbox, { recursive: true });
  const config = { mailbox: fileUrl(mailbox) + '/', allowEval: !!allowEval };
  writeFileSync(join(target, 'BridgeConfig.js'), `// Generated by studio-one-mcp setup\nvar BridgeConfig = ${JSON.stringify(config, null, 2)};\n`);
  return { target, config };
}

export function uninstallDevice(profile) {
  const target = deviceTarget(profile);
  rmSync(target, { recursive: true, force: true });
  return target;
}

export function readDeviceConfig(profile) {
  try {
    const text = readFileSync(join(deviceTarget(profile), 'BridgeConfig.js'), 'utf8');
    return JSON.parse(text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1));
  } catch {
    return null;
  }
}

// installed: files present; current: identical to this checkout's device/ folder.
export function deviceStatus(profile) {
  const target = deviceTarget(profile);
  if (!existsSync(join(target, 'StudioOneMCP.device'))) return { installed: false, current: false, config: null };
  const stale = readdirSync(deviceSource).filter((f) => {
    try {
      return readFileSync(join(deviceSource, f), 'utf8') !== readFileSync(join(target, f), 'utf8');
    } catch {
      return true;
    }
  });
  return { installed: true, current: stale.length === 0, stale, config: readDeviceConfig(profile) };
}
